# permissions for end users to view extractors.
apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRole
metadata:
  labels:
    app.kubernetes.io/name: kator
    app.kubernetes.io/managed-by: kustomize
  name: extractor-viewer-role
rules:
- apiGroups:
  - kator.my.domain
  resources:
  - extractors
  verbs:
  - get
  - list
  - watch
- apiGroups:
  - kator.my.domain
  resources:
  - extractors/status
  verbs:
  - get
