---
apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRole
metadata:
  name: manager-role
rules:
- apiGroups:
  - kator.my.domain
  resources:
  - extractorstatuses
  - pipelines
  verbs:
  - create
  - delete
  - get
  - list
  - patch
  - update
  - watch
- apiGroups:
  - kator.my.domain
  resources:
  - extractorstatuses/finalizers
  - pipelines/finalizers
  verbs:
  - update
- apiGroups:
  - kator.my.domain
  resources:
  - extractorstatuses/status
  - pipelines/status
  verbs:
  - get
  - patch
  - update
