# permissions for end users to view transformstatuses.
apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRole
metadata:
  labels:
    app.kubernetes.io/name: kator
    app.kubernetes.io/managed-by: kustomize
  name: transformstatus-viewer-role
rules:
- apiGroups:
  - kator.my.domain
  resources:
  - transformstatuses
  verbs:
  - get
  - list
  - watch
- apiGroups:
  - kator.my.domain
  resources:
  - transformstatuses/status
  verbs:
  - get
